In [425]:
import pandas as pd

In [426]:
# Cargar los datos de los a√±os
data_2021 = pd.read_csv('atp_matches_2021.csv')
data_2022 = pd.read_csv('atp_matches_2022.csv')
data_2023 = pd.read_csv('atp_matches_2023.csv')

# Agregar una columna 'source' a cada DataFrame
data_2021['source'] = 'atp_matches_2021.csv'
data_2022['source'] = 'atp_matches_2022.csv'
data_2023['source'] = 'atp_matches_2023.csv'

data_2021 = data_2021.reset_index(drop=True)
data_2022 = data_2022.reset_index(drop=True)
data_2023 = data_2023.reset_index(drop=True)
# Combinar los datos en un solo DataFrame
data_all = pd.concat([data_2021, data_2022, data_2023])

In [427]:
data_all

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,source
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0,atp_matches_2021.csv
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0,atp_matches_2021.csv
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0,atp_matches_2021.csv
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0,atp_matches_2021.csv
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0,atp_matches_2021.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2981,2023-M-DC-2023-WG2-PO-RSA-LUX-01,Davis Cup WG2 PO: RSA vs LUX,NaN,4,D,20230204,5,202335,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1717.0,1.0,atp_matches_2023.csv
2982,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,1,117365,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,990.0,11.0,279.0,190.0,atp_matches_2023.csv
2983,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,2,121411,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,364.0,131.0,894.0,15.0,atp_matches_2023.csv
2984,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,4,144949,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,894.0,15.0,285.0,184.0,atp_matches_2023.csv
2985,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,5,121411,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,364.0,131.0,990.0,11.0,atp_matches_2023.csv

In [428]:
len(data_2021) + len(data_2022) + len(data_2023)

8636

In [429]:
data_all['fecha_partido'] = pd.to_datetime(data_all['tourney_date'], format='%Y%m%d')

In [430]:
data_all = data_all.sort_values(by='fecha_partido')

In [431]:
data_all_sorted

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,source,fecha_partido
1164,2021-0499,Delray Beach,Hard,32,A,20210104,278,103333,NaN,NaN,...,21.0,15.0,5.0,8.0,148.0,444.0,59.0,1044.0,atp_matches_2021.csv,2021-01-04
1158,2021-0499,Delray Beach,Hard,32,A,20210104,271,106329,NaN,NaN,...,12.0,11.0,2.0,6.0,84.0,820.0,281.0,185.0,atp_matches_2021.csv,2021-01-04
1159,2021-0499,Delray Beach,Hard,32,A,20210104,272,200624,NaN,NaN,...,11.0,10.0,1.0,4.0,119.0,566.0,95.0,768.0,atp_matches_2021.csv,2021-01-04
1160,2021-0499,Delray Beach,Hard,32,A,20210104,273,126205,5.0,NaN,...,10.0,8.0,2.0,6.0,52.0,1080.0,268.0,205.0,atp_matches_2021.csv,2021-01-04
1161,2021-0499,Delray Beach,Hard,32,A,20210104,275,111815,NaN,NaN,...,7.0,7.0,4.0,8.0,74.0,877.0,299.0,165.0,atp_matches_2021.csv,2021-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2763,2023-7696,NextGen Finals,Hard,8,F,20231127,288,209098,6.0,NaN,...,12.0,15.0,9.0,11.0,110.0,582.0,97.0,653.0,atp_matches_2023.csv,2023-11-27
2764,2023-7696,NextGen Finals,Hard,8,F,20231127,287,209406,8.0,NaN,...,8.0,10.0,5.0,10.0,185.0,326.0,97.0,653.0,atp_matches_2023.csv,2023-11-27
2765,2023-7696,NextGen Finals,Hard,8,F,20231127,286,209098,6.0,NaN,...,14.0,12.0,0.0,2.0,110.0,582.0,185.0,326.0,atp_matches_2023.csv,2023-11-27
2753,2023-7696,NextGen Finals,Hard,8,F,20231127,298,209098,6.0,NaN,...,8.0,5.0,0.0,1.0,110.0,582.0,94.0,673.0,atp_matches_2023.csv,2023-11-27
2759,2023-7696,NextGen Finals,Hard,8,F,20231127,292,208134,7.0,NaN,...,20.0,15.0,3.0,5.0,115.0,549.0,100.0,640.0,atp_matches_2023.csv,2023-11-27

In [432]:
import numpy as np

In [433]:
data_all_sorted['head_to_head'] = 0.5
data_all_sorted = data_all_sorted.reset_index(drop=True)
# Calcula el h2h para cada partido y actualiza los valores existentes
for i in range(len(data_all_sorted)):
    jugador1 = data_all_sorted.iloc[i]['winner_id']
    jugador2 = data_all_sorted.iloc[i]['loser_id']
    fecha = data_all_sorted.iloc[i]['fecha_partido']
    new_data = data_all_sorted[((data_all_sorted['winner_id'] == jugador1) | (data_all_sorted['loser_id'] == jugador1)) &
                    ((data_all_sorted['winner_id'] == jugador2) | (data_all_sorted['loser_id'] == jugador2)) &
                    (data_all_sorted['fecha_partido'] < fecha)]
    if len(new_data) > 0:
        partidos_ganados = len(new_data[new_data['winner_id'] == jugador1])
        h2h = partidos_ganados / len(new_data)
        data_all_sorted.at[i, 'head_to_head'] = h2h

0 / 1 0.0
0.0
1 / 2 0.5
0.5
1 / 3 0.3333333333333333
0.3333333333333333
2 / 4 0.5
0.5

In [434]:
len(data_2021) + len(data_2022) + len(data_2023)

8636

In [435]:
len(data_all)

8636

In [436]:
data_all_sorted

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,source,fecha_partido,head_to_head
0,2021-0499,Delray Beach,Hard,32,A,20210104,278,103333,NaN,NaN,...,15.0,5.0,8.0,148.0,444.0,59.0,1044.0,atp_matches_2021.csv,2021-01-04,0.5
1,2021-0499,Delray Beach,Hard,32,A,20210104,271,106329,NaN,NaN,...,11.0,2.0,6.0,84.0,820.0,281.0,185.0,atp_matches_2021.csv,2021-01-04,0.5
2,2021-0499,Delray Beach,Hard,32,A,20210104,272,200624,NaN,NaN,...,10.0,1.0,4.0,119.0,566.0,95.0,768.0,atp_matches_2021.csv,2021-01-04,0.5
3,2021-0499,Delray Beach,Hard,32,A,20210104,273,126205,5.0,NaN,...,8.0,2.0,6.0,52.0,1080.0,268.0,205.0,atp_matches_2021.csv,2021-01-04,0.5
4,2021-0499,Delray Beach,Hard,32,A,20210104,275,111815,NaN,NaN,...,7.0,4.0,8.0,74.0,877.0,299.0,165.0,atp_matches_2021.csv,2021-01-04,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631,2023-7696,NextGen Finals,Hard,8,F,20231127,288,209098,6.0,NaN,...,15.0,9.0,11.0,110.0,582.0,97.0,653.0,atp_matches_2023.csv,2023-11-27,0.5
8632,2023-7696,NextGen Finals,Hard,8,F,20231127,287,209406,8.0,NaN,...,10.0,5.0,10.0,185.0,326.0,97.0,653.0,atp_matches_2023.csv,2023-11-27,0.5
8633,2023-7696,NextGen Finals,Hard,8,F,20231127,286,209098,6.0,NaN,...,12.0,0.0,2.0,110.0,582.0,185.0,326.0,atp_matches_2023.csv,2023-11-27,0.5
8634,2023-7696,NextGen Finals,Hard,8,F,20231127,298,209098,6.0,NaN,...,5.0,0.0,1.0,110.0,582.0,94.0,673.0,atp_matches_2023.csv,2023-11-27,0.5
8635,2023-7696,NextGen Finals,Hard,8,F,20231127,292,208134,7.0,NaN,...,15.0,3.0,5.0,115.0,549.0,100.0,640.0,atp_matches_2023.csv,2023-11-27,0.5

In [437]:
# Filtrar el DataFrame para encontrar el partido deseado
partido_buscado = data_all_sorted[(data_all_sorted['winner_id'] == 104925) & (data_all_sorted['loser_id'] == 207989) | (data_all_sorted['winner_id'] == 207989) & (data_all_sorted['loser_id'] == 104925)]
# Mostrar el resultado (si existe)
if not partido_buscado.empty:
    print("Partido encontrado:")
    print(partido_buscado)
else:
    print("No se encontr√≥ ning√∫n partido con los IDs especificados.")

Partido encontrado:
     tourney_id        tourney_name surface  draw_size tourney_level  \
3910  2022-1536      Madrid Masters    Clay         64             M
7054   2023-520       Roland Garros    Clay        128             G
7353   2023-540           Wimbledon   Grass        128             G
7791  2023-0422  Cincinnati Masters    Hard         64             M
8598  2023-0605         Tour Finals    Hard          8             A

      tourney_date  match_num  winner_id  winner_seed winner_entry  ...  \
3910      20220502        299     207989          7.0          NaN  ...
7054      20230529        224     104925          3.0          NaN  ...
7353      20230703        226     207989          1.0          NaN  ...
7791      20230814        300     104925          2.0          NaN  ...
8598      20231113        298     104925          1.0          NaN  ...

     l_SvGms l_bpSaved  l_bpFaced winner_rank  winner_rank_points  loser_rank  \
3910    18.0       8.0       10.0         9.0              3818.0         1.0
7054    17.0       5.0       12.0         3.0              5955.0         1.0
7353    24.0      14.0       19.0         1.0              7675.0         2.0
7791    18.0      13.0       16.0         2.0              8795.0         1.0
8598     8.0       5.0        8.0         1.0              9945.0         2.0

      loser_rank_points                source fecha_partido head_to_head
3910             8400.0  atp_matches_2022.csv    2022-05-02     0.500000
7054             6815.0  atp_matches_2023.csv    2023-05-29     0.000000
7353             7595.0  atp_matches_2023.csv    2023-07-03     0.500000
7791             9395.0  atp_matches_2023.csv    2023-08-14     0.333333
8598             8455.0  atp_matches_2023.csv    2023-11-13     0.500000

[5 rows x 52 columns]